version: '3.9'

services:
  web:
    restart: unless-stopped
    build:
      context: ./netology_pd_diplom
      dockerfile: Dockerfile
#    command: sh -c "python manage.py makemigrations &&
#              python manage.py migrate &&
#              gunicorn netology_pd_diplom.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_volume:/src/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.db
    volumes:
      - pg-data:/var/lib/postgresql/data/

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/src/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6379:6379"
    depends_on:
      - database

  celery_worker:
    build:
      context: ./netology_pd_diplom
      dockerfile: Dockerfile
    entrypoint: /src/celery_entrypoint.sh
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web

volumes:
    pg-data:
    static_volume:
